######################################################################
# Automatically generated by qmake (2.01a) ? 10? 8 04:28:42 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qtalk.cpp
